// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, title, description, organizer, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, organizer, created_at, updated_at, user_id
`

type CreateEventParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	Organizer   sql.NullString
	UserID      uuid.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Organizer,
		arg.UserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Organizer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1 AND user_id = $2
`

type DeleteEventParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, arg.ID, arg.UserID)
	return err
}

const getEventConfirmedUserReservations = `-- name: GetEventConfirmedUserReservations :many
SELECT 
	p.user_id,
	CONCAT(u.firstName, ' ', u.lastName) AS fullName, 
	u.email
FROM events as e
JOIN event_details AS ed
	ON ed.event_id = e.id
JOIN reservations AS r
	ON r.event_detail_id = ed.id
JOIN payments AS p
	ON p.id = r.payment_id
JOIN users AS u
	ON u.id = p.user_id 
WHERE e.id = $1
	AND p.status = 'succeeded'
GROUP BY p.user_id, u.firstName, u.lastName, u.email
`

type GetEventConfirmedUserReservationsRow struct {
	UserID   uuid.UUID
	Fullname sql.NullString
	Email    string
}

func (q *Queries) GetEventConfirmedUserReservations(ctx context.Context, id uuid.UUID) ([]GetEventConfirmedUserReservationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventConfirmedUserReservations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventConfirmedUserReservationsRow
	for rows.Next() {
		var i GetEventConfirmedUserReservationsRow
		if err := rows.Scan(&i.UserID, &i.Fullname, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvents = `-- name: GetEvents :many
SELECT 
	e.id AS event_id,
	e.title,
	e.description,
	e.organizer,
	ed.id AS event_detail_id,
	ed.show_date,
	ed.price,
	ed.number_of_tickets,
	ed.ticket_description
FROM events AS e
LEFT JOIN event_details AS ed
ON ed.event_id = e.id
WHERE 
(LOWER(e.title) LIKE $1 
OR LOWER(e.description) LIKE $2 
OR LOWER(e.organizer) LIKE $3) 
AND (ed.show_date >= $4 AND ed.show_date <= $5)
`

type GetEventsParams struct {
	Title       string
	Description string
	Organizer   sql.NullString
	ShowDate    time.Time
	ShowDate_2  time.Time
}

type GetEventsRow struct {
	EventID           uuid.UUID
	Title             string
	Description       string
	Organizer         sql.NullString
	EventDetailID     uuid.NullUUID
	ShowDate          sql.NullTime
	Price             sql.NullString
	NumberOfTickets   sql.NullInt32
	TicketDescription sql.NullString
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEvents,
		arg.Title,
		arg.Description,
		arg.Organizer,
		arg.ShowDate,
		arg.ShowDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsRow
	for rows.Next() {
		var i GetEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.Organizer,
			&i.EventDetailID,
			&i.ShowDate,
			&i.Price,
			&i.NumberOfTickets,
			&i.TicketDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaidEventForRefund = `-- name: GetPaidEventForRefund :many
SELECT
    p.id AS payment_id,
    p.payment_intent_id,
	p.user_id AS payer_user_id,
    p.amount,
    p.status,
	e.title,
	SUM(ed.price) AS ticket_price 
FROM events AS e
JOIN event_details AS ed
    ON ed.event_id = e.id
JOIN reservations AS r
    ON r.event_detail_id = ed.id
JOIN payments AS p
    ON p.id = r.payment_id
WHERE e.id = $1::uuid AND e.user_id = $2::uuid
GROUP BY p.id, p.payment_intent_id, p.user_id, p.amount, p.status, e.title, ed.price
`

type GetPaidEventForRefundParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

type GetPaidEventForRefundRow struct {
	PaymentID       uuid.UUID
	PaymentIntentID sql.NullString
	PayerUserID     uuid.UUID
	Amount          string
	Status          string
	Title           string
	TicketPrice     string
}

func (q *Queries) GetPaidEventForRefund(ctx context.Context, arg GetPaidEventForRefundParams) ([]GetPaidEventForRefundRow, error) {
	rows, err := q.db.QueryContext(ctx, getPaidEventForRefund, arg.EventID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaidEventForRefundRow
	for rows.Next() {
		var i GetPaidEventForRefundRow
		if err := rows.Scan(
			&i.PaymentID,
			&i.PaymentIntentID,
			&i.PayerUserID,
			&i.Amount,
			&i.Status,
			&i.Title,
			&i.TicketPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEventById = `-- name: GetUserEventById :one
SELECT id, title, description, organizer, created_at, updated_at, user_id
FROM events
WHERE id = $1 AND user_id = $2
`

type GetUserEventByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetUserEventById(ctx context.Context, arg GetUserEventByIdParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getUserEventById, arg.ID, arg.UserID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Organizer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserEvents = `-- name: GetUserEvents :many
SELECT id, title, description, organizer, created_at, updated_at, user_id 
FROM events
WHERE user_id = $1
`

func (q *Queries) GetUserEvents(ctx context.Context, userID uuid.UUID) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getUserEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Organizer,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $1, description = $2, organizer = $3, updated_at = NOW()
WHERE id = $4 AND user_id= $5
RETURNING id, title, description, organizer, created_at, updated_at, user_id
`

type UpdateEventParams struct {
	Title       string
	Description string
	Organizer   sql.NullString
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Title,
		arg.Description,
		arg.Organizer,
		arg.ID,
		arg.UserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Organizer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
