// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_details.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createEventDetail = `-- name: CreateEventDetail :one
INSERT INTO event_details (id, show_date, price, number_of_tickets, tickets_remaining, ticket_description, event_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, show_date, price, number_of_tickets, tickets_remaining, ticket_description, created_at, updated_at, event_id
`

type CreateEventDetailParams struct {
	ID                uuid.UUID
	ShowDate          time.Time
	Price             string
	NumberOfTickets   int32
	TicketsRemaining  int32
	TicketDescription string
	EventID           uuid.UUID
}

func (q *Queries) CreateEventDetail(ctx context.Context, arg CreateEventDetailParams) (EventDetail, error) {
	row := q.db.QueryRowContext(ctx, createEventDetail,
		arg.ID,
		arg.ShowDate,
		arg.Price,
		arg.NumberOfTickets,
		arg.TicketsRemaining,
		arg.TicketDescription,
		arg.EventID,
	)
	var i EventDetail
	err := row.Scan(
		&i.ID,
		&i.ShowDate,
		&i.Price,
		&i.NumberOfTickets,
		&i.TicketsRemaining,
		&i.TicketDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const deleteEventDetail = `-- name: DeleteEventDetail :exec
DELETE FROM event_details WHERE id = $1 AND event_id = $2
`

type DeleteEventDetailParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) DeleteEventDetail(ctx context.Context, arg DeleteEventDetailParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventDetail, arg.ID, arg.EventID)
	return err
}

const getEventDetailsByEventId = `-- name: GetEventDetailsByEventId :many
SELECT id, show_date, price, number_of_tickets, tickets_remaining, ticket_description, created_at, updated_at, event_id FROM event_details WHERE event_id = ANY($1)
`

func (q *Queries) GetEventDetailsByEventId(ctx context.Context, eventID []uuid.UUID) ([]EventDetail, error) {
	rows, err := q.db.QueryContext(ctx, getEventDetailsByEventId, pq.Array(eventID))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventDetail
	for rows.Next() {
		var i EventDetail
		if err := rows.Scan(
			&i.ID,
			&i.ShowDate,
			&i.Price,
			&i.NumberOfTickets,
			&i.TicketsRemaining,
			&i.TicketDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventDetailsById = `-- name: GetEventDetailsById :one
SELECT id, show_date, price, number_of_tickets, tickets_remaining, ticket_description, created_at, updated_at, event_id FROM event_details WHERE id = $1
`

func (q *Queries) GetEventDetailsById(ctx context.Context, id uuid.UUID) (EventDetail, error) {
	row := q.db.QueryRowContext(ctx, getEventDetailsById, id)
	var i EventDetail
	err := row.Scan(
		&i.ID,
		&i.ShowDate,
		&i.Price,
		&i.NumberOfTickets,
		&i.TicketsRemaining,
		&i.TicketDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const getPaidEventDetailForRefund = `-- name: GetPaidEventDetailForRefund :many
SELECT
    p.id AS payment_id,
    p.payment_intent_id,
    p.amount,
    p.status,
	e.title,
    ed.ticket_description,
	SUM(ed.price) AS ticket_price 
FROM events AS e
JOIN event_details AS ed
    ON ed.event_id = e.id
JOIN reservations AS r
    ON r.event_detail_id = ed.id
JOIN payments AS p
    ON p.id = r.payment_id
JOIN users AS u
    ON u.id = p.user_id
WHERE ed.id = $1::uuid AND e.user_id = $2::uuid
GROUP BY p.id, p.payment_intent_id, p.amount, p.status, e.title, ed.ticket_description, ed.price
`

type GetPaidEventDetailForRefundParams struct {
	EventDetailID uuid.UUID
	UserID        uuid.UUID
}

type GetPaidEventDetailForRefundRow struct {
	PaymentID         uuid.UUID
	PaymentIntentID   sql.NullString
	Amount            string
	Status            string
	Title             string
	TicketDescription string
	TicketPrice       string
}

func (q *Queries) GetPaidEventDetailForRefund(ctx context.Context, arg GetPaidEventDetailForRefundParams) ([]GetPaidEventDetailForRefundRow, error) {
	rows, err := q.db.QueryContext(ctx, getPaidEventDetailForRefund, arg.EventDetailID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaidEventDetailForRefundRow
	for rows.Next() {
		var i GetPaidEventDetailForRefundRow
		if err := rows.Scan(
			&i.PaymentID,
			&i.PaymentIntentID,
			&i.Amount,
			&i.Status,
			&i.Title,
			&i.TicketDescription,
			&i.TicketPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gethEventDetailsWithTitleByIds = `-- name: GethEventDetailsWithTitleByIds :many
SELECT 
	e.title,
	ed.ticket_description,
	ed.show_date
FROM event_details AS ed
JOIN events AS e
	ON e.id = ed.event_id
WHERE ed.id = ANY($1)
`

type GethEventDetailsWithTitleByIdsRow struct {
	Title             string
	TicketDescription string
	ShowDate          time.Time
}

func (q *Queries) GethEventDetailsWithTitleByIds(ctx context.Context, id []uuid.UUID) ([]GethEventDetailsWithTitleByIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, gethEventDetailsWithTitleByIds, pq.Array(id))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GethEventDetailsWithTitleByIdsRow
	for rows.Next() {
		var i GethEventDetailsWithTitleByIdsRow
		if err := rows.Scan(&i.Title, &i.TicketDescription, &i.ShowDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventDetail = `-- name: UpdateEventDetail :one
UPDATE event_details
SET show_date = $1, price = $2, number_of_tickets = $3, ticket_description = $4, updated_at = NOW()
WHERE id = $5 AND event_id = $6
RETURNING id, show_date, price, number_of_tickets, tickets_remaining, ticket_description, created_at, updated_at, event_id
`

type UpdateEventDetailParams struct {
	ShowDate          time.Time
	Price             string
	NumberOfTickets   int32
	TicketDescription string
	ID                uuid.UUID
	EventID           uuid.UUID
}

func (q *Queries) UpdateEventDetail(ctx context.Context, arg UpdateEventDetailParams) (EventDetail, error) {
	row := q.db.QueryRowContext(ctx, updateEventDetail,
		arg.ShowDate,
		arg.Price,
		arg.NumberOfTickets,
		arg.TicketDescription,
		arg.ID,
		arg.EventID,
	)
	var i EventDetail
	err := row.Scan(
		&i.ID,
		&i.ShowDate,
		&i.Price,
		&i.NumberOfTickets,
		&i.TicketsRemaining,
		&i.TicketDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}

const updateTicketsRemaining = `-- name: UpdateTicketsRemaining :one
UPDATE event_details
SET tickets_remaining = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, show_date, price, number_of_tickets, tickets_remaining, ticket_description, created_at, updated_at, event_id
`

type UpdateTicketsRemainingParams struct {
	TicketsRemaining int32
	ID               uuid.UUID
}

func (q *Queries) UpdateTicketsRemaining(ctx context.Context, arg UpdateTicketsRemainingParams) (EventDetail, error) {
	row := q.db.QueryRowContext(ctx, updateTicketsRemaining, arg.TicketsRemaining, arg.ID)
	var i EventDetail
	err := row.Scan(
		&i.ID,
		&i.ShowDate,
		&i.Price,
		&i.NumberOfTickets,
		&i.TicketsRemaining,
		&i.TicketDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}
