// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event_details.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEventDetail = `-- name: CreateEventDetail :one
INSERT INTO event_details (id, show_date, price, number_of_tickets, ticket_description, event_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, show_date, price, number_of_tickets, ticket_description, created_at, updated_at, event_id
`

type CreateEventDetailParams struct {
	ID                uuid.UUID
	ShowDate          time.Time
	Price             string
	NumberOfTickets   int32
	TicketDescription string
	EventID           uuid.UUID
}

func (q *Queries) CreateEventDetail(ctx context.Context, arg CreateEventDetailParams) (EventDetail, error) {
	row := q.db.QueryRowContext(ctx, createEventDetail,
		arg.ID,
		arg.ShowDate,
		arg.Price,
		arg.NumberOfTickets,
		arg.TicketDescription,
		arg.EventID,
	)
	var i EventDetail
	err := row.Scan(
		&i.ID,
		&i.ShowDate,
		&i.Price,
		&i.NumberOfTickets,
		&i.TicketDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}
