// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID          uuid.UUID
	Title       string
	Description string
	Organizer   sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	UserID      uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Firstname string
	Lastname  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
