// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID          uuid.UUID
	Title       string
	Description string
	Organizer   sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	UserID      uuid.UUID
}

type EventDetail struct {
	ID                uuid.UUID
	ShowDate          time.Time
	Price             string
	NumberOfTickets   int32
	TicketsRemaining  int32
	TicketDescription string
	CreatedAt         time.Time
	UpdatedAt         sql.NullTime
	EventID           uuid.UUID
}

type Payment struct {
	ID              uuid.UUID
	PaymentIntentID sql.NullString
	Amount          string
	Currency        string
	Status          string
	ExpiresAt       time.Time
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
	UserID          uuid.UUID
}

type PaymentLog struct {
	ID              uuid.UUID
	Status          string
	Description     sql.NullString
	PaymentIntentID string
	PaymentMethodID sql.NullString
	Amount          string
	CreatedAt       time.Time
	UserEmail       string
	PaymentID       uuid.UUID
}

type Reservation struct {
	ID            uuid.UUID
	Email         string
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	EventDetailID uuid.UUID
	UserID        uuid.UUID
	PaymentID     uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Firstname string
	Lastname  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
