// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, amount, currency, status, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, amount, currency, status, user_id
`

type CreatePaymentParams struct {
	ID       uuid.UUID
	Amount   string
	Currency string
	Status   string
	UserID   uuid.UUID
}

type CreatePaymentRow struct {
	ID       uuid.UUID
	Amount   string
	Currency string
	Status   string
	UserID   uuid.UUID
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.UserID,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.UserID,
	)
	return i, err
}

const restoreTicketsAndDeletePayment = `-- name: RestoreTicketsAndDeletePayment :exec
WITH counts AS (
  SELECT event_detail_id, COUNT(*) AS cnt
  FROM reservations
  WHERE payment_id = $1::uuid
  GROUP BY event_detail_id
),
updated AS (
  -- add back reserved tickets
  UPDATE event_details ed
  SET tickets_remaining = ed.tickets_remaining + c.cnt
  FROM counts c
  WHERE ed.id = c.event_detail_id
  RETURNING ed.id
)
DELETE FROM payments
WHERE id = $1::uuid AND user_id = $2::uuid
`

type RestoreTicketsAndDeletePaymentParams struct {
	PaymentID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RestoreTicketsAndDeletePayment(ctx context.Context, arg RestoreTicketsAndDeletePaymentParams) error {
	_, err := q.db.ExecContext(ctx, restoreTicketsAndDeletePayment, arg.PaymentID, arg.UserID)
	return err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET amount = $1, status = $2, updated_at = NOW(), payment_intent_id = $3
WHERE id = $4 AND user_id = $5
RETURNING id, amount, currency, status, user_id
`

type UpdatePaymentParams struct {
	Amount          string
	Status          string
	PaymentIntentID sql.NullString
	ID              uuid.UUID
	UserID          uuid.UUID
}

type UpdatePaymentRow struct {
	ID       uuid.UUID
	Amount   string
	Currency string
	Status   string
	UserID   uuid.UUID
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (UpdatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, updatePayment,
		arg.Amount,
		arg.Status,
		arg.PaymentIntentID,
		arg.ID,
		arg.UserID,
	)
	var i UpdatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.UserID,
	)
	return i, err
}
