// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, amount, currency, status, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, amount, currency, status, user_id
`

type CreatePaymentParams struct {
	ID       uuid.UUID
	Amount   string
	Currency string
	Status   string
	UserID   uuid.UUID
}

type CreatePaymentRow struct {
	ID       uuid.UUID
	Amount   string
	Currency string
	Status   string
	UserID   uuid.UUID
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.UserID,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.UserID,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET amount = $1, status = $2, updated_at = NOW()
RETURNING id, amount, currency, status, user_id
`

type UpdatePaymentParams struct {
	Amount string
	Status string
}

type UpdatePaymentRow struct {
	ID       uuid.UUID
	Amount   string
	Currency string
	Status   string
	UserID   uuid.UUID
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (UpdatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, updatePayment, arg.Amount, arg.Status)
	var i UpdatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.UserID,
	)
	return i, err
}
