// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, amount, currency, status, expires_at, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, payment_intent_id, amount, currency, status, expires_at, created_at, updated_at, user_id
`

type CreatePaymentParams struct {
	ID        uuid.UUID
	Amount    string
	Currency  string
	Status    string
	ExpiresAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.ExpiresAt,
		arg.UserID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentIntentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getPaymentById = `-- name: GetPaymentById :one
SELECT id, payment_intent_id, amount, currency, status, expires_at, created_at, updated_at, user_id FROM payments WHERE id = $1 AND user_id = $2
`

type GetPaymentByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPaymentById(ctx context.Context, arg GetPaymentByIdParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentById, arg.ID, arg.UserID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentIntentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getPaymentByIdOnly = `-- name: GetPaymentByIdOnly :one
SELECT id, payment_intent_id, amount, currency, status, expires_at, created_at, updated_at, user_id FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByIdOnly(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIdOnly, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentIntentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserPayments = `-- name: GetUserPayments :many
SELECT id, payment_intent_id, amount, currency, status, expires_at, created_at, updated_at, user_id FROM payments WHERE user_id = $1
`

func (q *Queries) GetUserPayments(ctx context.Context, userID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getUserPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PaymentIntentID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTicketsAndDeletePayment = `-- name: RestoreTicketsAndDeletePayment :exec
WITH counts AS (
  SELECT event_detail_id, COUNT(*) AS cnt
  FROM reservations
  WHERE payment_id = $1::uuid
  GROUP BY event_detail_id
),
updated AS (
  UPDATE event_details ed
  SET tickets_remaining = ed.tickets_remaining + c.cnt
  FROM counts c
  WHERE ed.id = c.event_detail_id
  RETURNING ed.id
)
DELETE FROM payments
WHERE id = $1::uuid
  AND user_id = $2::uuid
  AND EXISTS (SELECT 1 FROM updated)
`

type RestoreTicketsAndDeletePaymentParams struct {
	PaymentID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RestoreTicketsAndDeletePayment(ctx context.Context, arg RestoreTicketsAndDeletePaymentParams) error {
	_, err := q.db.ExecContext(ctx, restoreTicketsAndDeletePayment, arg.PaymentID, arg.UserID)
	return err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET amount = $1, status = $2, updated_at = NOW(), payment_intent_id = $3
WHERE id = $4 AND user_id = $5
RETURNING id, payment_intent_id, amount, currency, status, expires_at, created_at, updated_at, user_id
`

type UpdatePaymentParams struct {
	Amount          string
	Status          string
	PaymentIntentID sql.NullString
	ID              uuid.UUID
	UserID          uuid.UUID
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePayment,
		arg.Amount,
		arg.Status,
		arg.PaymentIntentID,
		arg.ID,
		arg.UserID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentIntentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
