// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_logs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPaymentLog = `-- name: CreatePaymentLog :one
INSERT INTO payment_logs (id, status, description, payment_intent_id, payment_method_id, amount, user_email, payment_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, status, description, payment_intent_id, payment_method_id, amount, created_at, user_email, payment_id
`

type CreatePaymentLogParams struct {
	ID              uuid.UUID
	Status          string
	Description     sql.NullString
	PaymentIntentID string
	PaymentMethodID sql.NullString
	Amount          string
	UserEmail       string
	PaymentID       uuid.UUID
}

func (q *Queries) CreatePaymentLog(ctx context.Context, arg CreatePaymentLogParams) (PaymentLog, error) {
	row := q.db.QueryRowContext(ctx, createPaymentLog,
		arg.ID,
		arg.Status,
		arg.Description,
		arg.PaymentIntentID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.UserEmail,
		arg.PaymentID,
	)
	var i PaymentLog
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Description,
		&i.PaymentIntentID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.CreatedAt,
		&i.UserEmail,
		&i.PaymentID,
	)
	return i, err
}
