// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const reserveTicket = `-- name: ReserveTicket :one
WITH params AS (
    SELECT 
        $1::uuid AS event_detail_id, 
        $2::uuid AS reservation_id, 
        $3::text AS email,
        $4::uuid AS user_id), 
updated_event_detail AS ( 
    UPDATE event_details ed 
    SET tickets_remaining = ed.tickets_remaining - 1 
    FROM params p 
    WHERE ed.id = p.event_detail_id AND ed.tickets_remaining > 0 
    RETURNING ed.id AS event_detail_id ) 

INSERT INTO reservations (id, email, event_detail_id, user_id) 
SELECT 
    p.reservation_id AS id, 
    p.email AS email, 
    u.event_detail_id,
    p.user_id AS user_id
FROM params p 
CROSS JOIN updated_event_detail u 
RETURNING id AS id, email AS email, created_at AS created_at, updated_at AS updated_at, event_detail_id AS event_detail_id, user_id AS user_id
`

type ReserveTicketParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Column3 string
	Column4 uuid.UUID
}

func (q *Queries) ReserveTicket(ctx context.Context, arg ReserveTicketParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, reserveTicket,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventDetailID,
		&i.UserID,
	)
	return i, err
}
